version: '3.0'

services:

  postgres:
    image: postgres:alpine
    container_name: my_little_garden
    restart: always
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
    ports:
      - 5432:${PG_PORT}

